<?php

return [
    'doodle-alternativ' => [
        'path' => '/doodle-alternativ',
        'title' => 'Doodle alternativ – find en dato, der passer alle',
        'seo_title' => 'Doodle alternativ – Find en dato, der passer alle | Kanvi',
        'description' => 'Leder du efter et enkelt alternativ til Doodle? Med Kanvi kan I hurtigt finde en dato, der passer gruppen. Opret en datoafstemning og del linket.',
        'label' => 'Doodle alternativ',
        'group' => 'Kom godt i gang',
        'kind' => 'guide',
    ],
    'datoafstemning' => [
        'path' => '/datoafstemning',
        'title' => 'Datoafstemning – den nemme måde at finde en dato, der passer alle',
        'seo_title' => 'Datoafstemning – Find en dato der passer alle | Kanvi',
        'description' => 'Opret en enkel datoafstemning og find hurtigt den dag, der passer flest. Foreslå datoer, del linket og få alles svar samlet med Kanvi.',
        'label' => 'Datoafstemning',
        'group' => 'Kom godt i gang',
        'kind' => 'guide',
    ],
    'find-en-dato' => [
        'path' => '/find-en-dato',
        'title' => 'Sådan finder du en dato, der passer alle',
        'seo_title' => 'Sådan finder du en dato, der passer alle | Kanvi',
        'description' => 'Skal I finde en dato, hvor flest muligt kan? Her får du en enkel metode til at finde en fælles dato uden endeløse beskeder frem og tilbage.',
        'label' => 'Find en dato',
        'group' => 'Kom godt i gang',
        'kind' => 'guide',
    ],
    'julefrokost' => [
        'path' => '/til/julefrokost',
        'title' => 'Sådan finder I datoen til årets julefrokost',
        'seo_title' => 'Find dato til julefrokost – Sådan gør I det nemt | Kanvi',
        'description' => 'Skal I finde en dato til julefrokosten? Få en enkel metode til at samle alles svar og finde den dag, der passer flest.',
        'label' => 'Julefrokost',
        'group' => 'Vælg en anledning',
        'kind' => 'guide',
    ],
    'bestyrelser' => [
        'path' => '/til/bestyrelser',
        'title' => 'Sådan finder bestyrelsen en dato til næste møde',
        'seo_title' => 'Find dato til bestyrelsesmøde | Kanvi',
        'description' => 'Skal bestyrelsen finde en dato til næste møde? Saml alles svar ét sted og find hurtigt den dag, der passer bedst.',
        'label' => 'Bestyrelser',
        'group' => 'Vælg en anledning',
        'kind' => 'guide',
    ],
    'foreninger' => [
        'path' => '/til/foreninger',
        'title' => 'Find en dato i foreningen – uden lange beskedtråde',
        'seo_title' => 'Find en dato i foreningen | Kanvi',
        'description' => 'Skal foreningen finde en dato til møde, arbejdsdag eller arrangement? Saml alles svar ét sted og find hurtigt den dag, der passer bedst.',
        'label' => 'Foreninger',
        'group' => 'Vælg en anledning',
        'kind' => 'guide',
    ],
    'venner' => [
        'path' => '/til/venner',
        'title' => 'Sådan finder I en dag, hvor vennerne faktisk kan ses',
        'seo_title' => 'Find en dag med vennerne | Kanvi',
        'description' => 'Svært at finde en dag, hvor alle vennerne kan? Foreslå nogle datoer, del et link og find hurtigt den dag, der passer bedst.',
        'label' => 'Venner',
        'group' => 'Vælg en anledning',
        'kind' => 'guide',
    ],
    'familien' => [
        'path' => '/til/familien',
        'title' => 'Sådan finder familien en dato, der passer alle',
        'seo_title' => 'Find en dato med familien | Kanvi',
        'description' => 'Skal familien finde en fælles dato til fødselsdag, middag eller sammenkomst? Saml alles svar ét sted og find hurtigt den dag, der passer bedst.',
        'label' => 'Familien',
        'group' => 'Vælg en anledning',
        'kind' => 'guide',
    ],
    'klassearrangement' => [
        'path' => '/til/klassearrangement',
        'title' => 'Sådan finder I en dato til klassearrangementet',
        'seo_title' => 'Find dato til klassearrangement | Kanvi',
        'description' => 'Skal klassen finde en dato til klassefest, fælles aktivitet eller forældremøde? Saml familiers svar ét sted og find den dag, der passer bedst.',
        'label' => 'Klassearrangement',
        'group' => 'Vælg en anledning',
        'kind' => 'guide',
    ],
    'polterabend' => [
        'path' => '/til/polterabend',
        'title' => 'Sådan finder I en dato til polterabend',
        'seo_title' => 'Find dato til polterabend | Kanvi',
        'description' => 'Skal I finde en dato til polterabend? Foreslå nogle muligheder, saml alles svar ét sted og find den dag, der passer bedst.',
        'label' => 'Polterabend',
        'group' => 'Vælg en anledning',
        'kind' => 'guide',
    ],

    // Informational pages. They share the article renderer, routes and sitemap,
    // but they are not guides and the guide index leaves them out.
    'faq' => [
        'path' => '/faq',
        'title' => 'Spørgsmål og svar om Kanvi',
        'seo_title' => 'Spørgsmål og svar | Kanvi',
        'description' => 'Svar på det, folk oftest spørger om: konto, deling, ændring af svar, hvem der kan se hvad, og hvor længe en afstemning bliver gemt.',
        'label' => 'Spørgsmål og svar',
        'group' => 'Om Kanvi',
        'kind' => 'page',
    ],
    'privatliv' => [
        'path' => '/privatliv',
        'title' => 'Privatliv og data',
        'seo_title' => 'Privatliv og data | Kanvi',
        'description' => 'Hvad Kanvi gemmer, hvem der kan se det, hvor længe det bliver gemt, og hvordan du får dine data slettet.',
        'label' => 'Privatliv',
        'group' => 'Om Kanvi',
        'kind' => 'page',
    ],
];
